theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "always"
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
